name: Other architectures

on:
  push:
    branches:
      - master
      - v*/dev
      - ci/*
      - dev/*
    paths:
      - '.github/workflows/arch.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'tests/unittests/**'
      - '**/CMakeLists.txt'
  pull_request:
    branches:
      - master
      - v*/dev
      - ci/*
      - dev/*
    paths:
      - '.github/workflows/arch.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'tests/unittests/**'
      - '**/CMakeLists.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}-${{ github.event.schedule }}
  cancel-in-progress: true

env:
  CCACHE_ABSSTDERR: true
  CCACHE_COMPRESS: true
  CCACHE_COMPRESSLEVEL: 6
  CCACHE_MAXSIZE: 50M
  CCACHE_NOHASHDIR: true
  CCACHE_SLOPPINESS: "pch_defines,time_macros"
  CCACHE_UNIFY: true

jobs:
  # Cross-compile on x64 host, then run tests on target architectures through QEMU
  cross-compile:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        # All targets supported by cross-compile-action
        target:
          - i686
          - armv5
          - armv6
          - armv7
          - aarch64
          - alpha
          - hppa
          - loongarch64
          - m68k
          - mips
          - mipsel
          - mips64
          - mips64el
          - mips32r6
          - mips32r6el
          - mips64r6
          - mips64r6el
          - powerpc
          - ppc64
          - ppc64le
          - riscv64
          - s390x
          - sh4
          - sparc64
        exclude:
          # Obsolete, and has nothing that other targets don't already cover:
          # little-endian, 64-bit, binary128 long double
          - target: alpha
          # Obsolete, and has nothing that other targets don't already cover:
          # little-endian, 32-bit, long double == double
          - target: sh4
          # Legacy NaN encoding is covered by mips (32-bit big-endian)
          # and mips64el (64-bit little-endian)
          - target: mipsel
          - target: mips64
          # IEEE 754-2008 NaN encoding on MIPS is covered by mips64r6el
          - target: mips32r6
          - target: mips32r6el
          - target: mips64r6

    env:
      CCACHE_DIR: "/tmp/ccache"
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install build tools
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq ninja-build ccache

      - name: Set up cross-compilation environment
        uses: eliaskosunen/cross-compile-action@master
        with:
          target: ${{ matrix.target }}

      - name: Load ccache
        uses: actions/cache@v6
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-arch-${{ matrix.target }}-${{ github.sha }}
          restore-keys: |
            ccache-arch-${{ matrix.target }}-${{ github.ref }}
            ccache-arch-${{ matrix.target }}-${{ github.base_ref }}
            ccache-arch-${{ matrix.target }}

      - name: Set up ccache
        run: |
          ccache --version
          ccache --zero-stats
          ccache --show-stats
          ccache --show-config

      - name: Cross-compile
        run: |
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DSCN_WERROR=OFF \
            ..
          cmake --build . --verbose -- -k 0

      - name: Show ccache stats
        run: ccache --show-stats

      - name: Run tests
        run: ctest --test-dir build --output-on-failure -R '^scn_(impl_)?tests$'

  # Cross-compile with Visual Studio, targeting arm64
  # Doesn't run tests

  cross-compile-msvc-arm64:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - gen: Visual Studio 17 2022
            arch: ARM64

    env:
      CCACHE_DIR: D:/ccache
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{ runner.workspace }}/build
          choco install ccache

      - name: Load ccache
        uses: actions/cache@v6
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-Windows-win2022-msvc${{ matrix.arch }}-std17-${{ github.sha }}
          restore-keys: |
            ccache-Windows-win2022-msvc${{ matrix.arch }}-std17-${{ github.ref }}
            ccache-Windows-win2022-msvc${{ matrix.arch }}-std17-${{ github.base_ref }}
            ccache-Windows-win2022-msvc${{ matrix.arch }}-std17

      - name: Run CMake
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: |
          cmake -G "${{ matrix.gen }}" -A ${{ matrix.arch }} -DCMAKE_CROSSCOMPILING=ON \
                -DSCN_DISABLE_REGEX=ON -DCMAKE_CXX_STANDARD=17 \
                -DSCN_CI=ON $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --parallel --verbose

  # Build and run test on native arm64 Ubuntu

  native-arm-linux:
    runs-on: ubuntu-${{ matrix.os }}-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 26.04
            cxx: g++-15
          - os: 26.04
            cxx: clang++-22
          - os: 24.04
            cxx: g++-14
          - os: 24.04
            cxx: clang++-18

    env:
      CXX: ${{ matrix.cxx }}
      OS: ${{ matrix.os }}

    steps:
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Create Build Environment
        run: |
          mkdir ${{ runner.workspace }}/build

      - name: Checkout
        uses: actions/checkout@v7

      - name: Run CMake
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake -G Ninja -DSCN_CI=ON -DCMAKE_BUILD_TYPE=Debug $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake --build . --verbose -- -k 0

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        run: |
          ctest --output-on-failure

  # Build and run test on native arm64 Windows

  native-arm-windows:
    runs-on: windows-${{ matrix.os }}-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 11
            type: Debug

    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Create build environment
        run: |
          cmake -E make_directory ${{ runner.workspace }}/build

      - name: Checkout
        uses: actions/checkout@v7

      - name: Run CMake
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: |
          cmake -DSCN_CI=ON $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake --build . --config ${{ matrix.type }} --parallel

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        run: |
          ctest -C ${{ matrix.type }} --output-on-failure
