name: Other architectures

on:
  push:
    branches:
      - master
      - v*/dev
      - ci/*
      - dev/*
    paths:
      - '.github/workflows/arch.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'tests/unittests/**'
      - '**/CMakeLists.txt'
  pull_request:
    branches:
      - master
      - v*/dev
      - ci/*
      - dev/*
    paths:
      - '.github/workflows/arch.yml'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'tests/unittests/**'
      - '**/CMakeLists.txt'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}-${{ github.event.schedule }}
  cancel-in-progress: true

env:
  CCACHE_ABSSTDERR: true
  CCACHE_COMPRESS: true
  CCACHE_COMPRESSLEVEL: 6
  CCACHE_MAXSIZE: 50M
  CCACHE_NOHASHDIR: true
  CCACHE_SLOPPINESS: "pch_defines,time_macros"
  CCACHE_UNIFY: true

jobs:
  # Cross-compile on x64 host, then run tests on target architectures through QEMU
  cross-compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: armv5
            triple: arm-linux-gnueabi
            cmake_processor: arm
            arch: none
            distro: none
            base_image: --platform=linux/arm/v5 arm32v5/debian:bookworm-backports

          - name: armv6
            triple: arm-linux-gnueabi
            cmake_processor: arm
            arch: armv6
            distro: bookworm

          - name: armv7
            triple: arm-linux-gnueabihf
            cmake_processor: arm
            arch: armv7
            distro: bookworm

          - name: aarch64
            triple: aarch64-linux-gnu
            cmake_processor: aarch64
            arch: aarch64
            distro: bookworm

          - name: s390x
            triple: s390x-linux-gnu
            cmake_processor: s390x
            arch: s390x
            distro: bookworm

          - name: ppc64le
            triple: powerpc64le-linux-gnu
            cmake_processor: ppc64le
            arch: ppc64le
            distro: bookworm

          - name: riscv64
            triple: riscv64-linux-gnu
            cmake_processor: riscv64
            arch: riscv64
            distro: ubuntu24.04

          - name: i386
            triple: i686-linux-gnu
            cmake_processor: i686
            arch: none
            distro: none
            base_image: --platform=linux/i386 i386/debian:bookworm-backports

          - name: mips64le
            triple: mips64el-linux-gnuabi64
            cmake_processor: mips64el
            arch: none
            distro: none
            base_image: --platform=linux/mips64le mips64le/debian:bookworm
            # Enable larger binary sizes
            cxx_flags: -mxgot

    env:
      CCACHE_DIR: "/tmp/ccache"
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install cross-compiler
        run: |
          sudo apt-get update -yq
          sudo apt-get install -yq ninja-build ccache gcc-${{ matrix.triple }} g++-${{ matrix.triple }}

      - name: Load ccache
        uses: actions/cache@v6
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-arch-${{ matrix.name }}-${{ github.sha }}
          restore-keys: |
            ccache-arch-${{ matrix.name }}-${{ github.ref }}
            ccache-arch-${{ matrix.name }}-${{ github.base_ref }}
            ccache-arch-${{ matrix.name }}

      - name: Cross-compile
        run: |
          ccache --version
          ccache --zero-stats
          ccache --show-stats
          ccache --show-config

          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_TOOLCHAIN_FILE=../cmake/cross-linux-gcc.cmake \
            -DCROSS_TRIPLE=${{ matrix.triple }} \
            -DCROSS_SYSTEM_PROCESSOR=${{ matrix.cmake_processor }} \
            -DCMAKE_C_FLAGS="${{ matrix.cxx_flags }}" \
            -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }}" \
            -DCMAKE_EXE_LINKER_FLAGS="-static" \
            -DSCN_DISABLE_TOP_PROJECT=ON \
            -DSCN_PEDANTIC=ON \
            -DSCN_WERROR=OFF \
            -DSCN_TESTS=ON \
            ..

          cmake --build . --verbose -- -k 0
          ccache --show-stats

      - name: Run tests
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          base_image: ${{ matrix.base_image }}

          githubToken: ${{ github.token }}

          dockerRunArgs: |
            --volume "${{ github.workspace }}:/workspace"

          # Setting GITHUB_WORKFLOW as a hack around https://github.com/uraimo/run-on-arch-action/issues/55
          env: |
            GITHUB_WORKFLOW: ${{ github.workflow }}-${{ github.job }}-${{ matrix.name }}

          run: |
            cd /workspace
            ./build/tests/unittests/scn_tests
            ./build/tests/unittests/scn_impl_tests

  # Cross-compile with Visual Studio, targeting arm64
  # Doesn't run tests

  cross-compile-msvc-arm64:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - gen: Visual Studio 17 2022
            arch: ARM64

    env:
      CCACHE_DIR: D:/ccache
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Create Build Environment
        run: |
          cmake -E make_directory ${{ runner.workspace }}/build
          choco install ccache

      - name: Load ccache
        uses: actions/cache@v6
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-Windows-win2022-msvc${{ matrix.arch }}-std17-${{ github.sha }}
          restore-keys: |
            ccache-Windows-win2022-msvc${{ matrix.arch }}-std17-${{ github.ref }}
            ccache-Windows-win2022-msvc${{ matrix.arch }}-std17-${{ github.base_ref }}
            ccache-Windows-win2022-msvc${{ matrix.arch }}-std17

      - name: Run CMake
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: |
          cmake -G "${{ matrix.gen }}" -A ${{ matrix.arch }} -DCMAKE_CROSSCOMPILING=ON \
                -DSCN_DISABLE_REGEX=ON -DCMAKE_CXX_STANDARD=17 \
                -DSCN_CI=ON $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: cmake --build . --parallel --verbose

  # Build and run test on native arm64 Ubuntu

  native-arm-linux:
    runs-on: ubuntu-${{ matrix.os }}-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 26.04
            cxx: g++-15
          - os: 26.04
            cxx: clang++-22
          - os: 24.04
            cxx: g++-14
          - os: 24.04
            cxx: clang++-18

    env:
      CXX: ${{ matrix.cxx }}
      OS: ${{ matrix.os }}

    steps:
      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Create Build Environment
        run: |
          mkdir ${{ runner.workspace }}/build

      - name: Checkout
        uses: actions/checkout@v7

      - name: Run CMake
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake -G Ninja -DSCN_CI=ON -DCMAKE_BUILD_TYPE=Debug $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake --build . --verbose -- -k 0

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        run: |
          ctest --output-on-failure

  # Build and run test on native arm64 Windows

  native-arm-windows:
    runs-on: windows-${{ matrix.os }}-arm
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 11
            type: Debug

    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Create build environment
        run: |
          cmake -E make_directory ${{ runner.workspace }}/build

      - name: Checkout
        uses: actions/checkout@v7

      - name: Run CMake
        working-directory: ${{ runner.workspace }}/build
        shell: bash
        run: |
          cmake -DSCN_CI=ON $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{ runner.workspace }}/build
        run: |
          cmake --build . --config ${{ matrix.type }} --parallel

      - name: Test
        working-directory: ${{ runner.workspace }}/build
        run: |
          ctest -C ${{ matrix.type }} --output-on-failure
